# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
    adapter: mysql
    database: luxury2
    username: root
    password: 999999
    host: 127.0.0.1
    socket: /opt/lampp/var/mysql/mysql.sock


  
test:
  adapter: mysql
  host: localhost
  database: lrm_test
  username: root
