# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: luxury2
  username: postgres
  password: 999999
  host: localhost
  port: 5432


  
test:
  adapter: mysql
  host: localhost
  database: lrm_test
  username: root
